name: Dependency audit

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

jobs:
  osv-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.6.0
    with:
      scan-args: |-
        --include-git-root
        --recursive
        --no-resolve
        ./
